version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    container_name: e-commerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    restart: unless-stopped

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payments
      - orders
    restart: unless-stopped

  payments:
      build:
        context: .
        dockerfile: ./payments/cmd/Dockerfile
      container_name: payments-service
      ports:
        - "8081:8081"
      environment:
        PORT: 8081
        DB_CONNECTION_STRING: postgres://user:password@postgres-payments:5432/payments?sslmode=disable
        RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
        MIGRATIONS_DIR: ./migrations
      volumes:
        - ./payments/migrations:/root/migrations
      depends_on:
        - postgres-payments
        - rabbitmq
      restart: unless-stopped
  orders:
      build:
        context: .
        dockerfile: ./orders/cmd/Dockerfile
      container_name: orders-service
      ports:
        - "8082:8082"
      environment:
        PORT: 8082
        DB_CONNECTION_STRING: postgres://user:password@postgres-orders:5432/orders?sslmode=disable
        RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
        MIGRATIONS_DIR: ./migrations
      volumes:
        - ./orders/migrations:/root/migrations
      depends_on:
        - postgres-orders
        - rabbitmq
      restart: unless-stopped
  postgres-payments:
    image: postgres:15
    container_name: postgres-payments-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
  postgres-orders:
    image: postgres:15
    container_name: postgres-orders-db
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password